language: bash

sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - shellcheck *.sh extras/*.sh
 - sudo sed -i "/debian unstable/d" /etc/apt/sources.list
 - sudo sh vpnsetup.sh
